[Interface]
PrivateKey = UKywXSXL+JFxVaorb+IqEOt2uimN6GHs0zTFZJK6q30=
Address = 10.0.0.100/32
DNS = 8.8.8.8

[Peer]
PublicKey = wNnwGrPTkK2AFrrSqG/HfF1G+cQVpc74PE9QFyFc/n4=
Endpoint = 165.22.89.182:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 20
