#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI1 -d I II III IV V
bspc monitor VGA1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a Brave-browser desktop='^6' follow=on
bspc rule -a Chromium desktop='^6' follow=on
# Spotify rule doesn't work if not install spotifywm-git
bspc rule -a Spotify desktop='^3'
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
