require("options")
require("plugins")
require("nvim-tree-config")
require("lualine-config")
require("treesitter-config")
require("autopairs-config")
require("keybindings")
require("whichkey-config")
require("telescope-config")
require("lsp")
require("colorizer-config")
require("gitsigns-config")
require("formatter-config")
require("comment-config")
require("toggleterm-config")
vim.cmd("colorscheme nord")
