;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	   ______      __
;;	  / ____/___  / /___  __________
;;	 / /   / __ \/ / __ \/ ___/ ___/
;;	/ /___/ /_/ / / /_/ / /  (__  )
;;	\____/\____/_/\____/_/  /____/
;;
;; Created By Aditya Shakya @adi1090x
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
[color]
;background = ${xrdb:color0:#222}
background = #331E1E1E
background-alt = #bf1e1e1e
;foreground = ${xrdb:color7:#222}
foreground = #ffffff
;foreground = #33ffff
foreground-alt = #ffffff
primary = #1b9fc6
secondary = #ffffff
alert = #e53935

trans = #0000000
white = #ffffff
black = #000000

;; Material Colors

red = #e53935
pink = #d81b60
purple = #8e24aa
deep-purple = #5e35b1
indigo = #3949ab
blue = #1e88e5
light-blue = #039be5
cyan = #00acc1
teal = #00897b
green = #43a047
light-green = #7cb342
lime = #c0ca33
yellow = #fdd835
amber = #ffb300
orange = #fb8c00
deep-orange = #f4511e
brown = #6d4c41
grey = #757575
blue-gray = #546e7a

;; Material Colors Shades

; Amber
amber800 = #FF6F00
amber700 = #FF8F00
amber600 = #FFA000
amber500 = #FFB300
amber400 = #FFC107
amber300 = #FFCA28
amber200 = #FFD54F
amber100 = #FFE082

; Blue
blshade8 = #0D47A1
blshade7 = #1565C0
blshade6 = #1976D2
blshade5 = #1E88E5
blshade4 = #2196F3
blshade3 = #42A5F5
blshade2 = #64B5F6
blshade1 = #90CAF9

; Blue-Grey
bgshade8 = #263238
bgshade7 = #37474F
bgshade6 = #455A64
bgshade5 = #546E7A
bgshade4 = #607D8B
bgshade3 = #78909C
bgshade2 = #90A4AE
bgshade1 = #B0BEC5

; Brown
brshade8 = #3E2723
brshade7 = #4E342E
brshade6 = #5D4037
brshade5 = #6D4C41
brshade4 = #795548
brshade3 = #8D6E63
brshade2 = #A1887F
brshade1 = #BCAAA4

; Cyan
cyshade8 = #006064
cyshade7 = #00838F
cyshade6 = #0097A7
cyshade5 = #00ACC1
cyshade4 = #00BCD4
cyshade3 = #26C6DA
cyshade2 = #4DD0E1
cyshade1 = #80DEEA

; Deep-Orange
doshade8 = #BF360C
doshade7 = #D84315
doshade6 = #E64A19
doshade5 = #F4511E
doshade4 = #FF5722
doshade3 = #FF7043
doshade2 = #FF8A65
doshade1 = #FFAB91

; Deep-Purple
dpshade8 = #311B92
dpshade7 = #4527A0
dpshade6 = #512DA8
dpshade5 = #5E35B1
dpshade4 = #673AB7
dpshade3 = #7E57C2
dpshade2 = #9575CD
dpshade1 = #B39DDB

; Green
green800 = #1B5E20
green700 = #2E7D32
green600 = #388E3C
green500 = #43A047
green400 = #4CAF50
green300 = #66BB6A
green200 = #81C784
green100 = #A5D6A7

; Grey
greshade8 = #212121
greshade7 = #424242
greshade6 = #616161
greshade5 = #757575
greshade4 = #9E9E9E
greshade3 = #BDBDBD
greshade2 = #D4D4D4
greshade1 = #EEEEEE

; Indigo
inshade8 = #1A237E
inshade7 = #283593
inshade6 = #303F9F
inshade5 = #3949AB
inshade4 = #3F51B5
inshade3 = #5C6BC0
inshade2 = #7986CB
inshade1 = #9FA8DA

; Light-Blue
lbshade8 = #01579B
lbshade7 = #0277BD
lbshade6 = #0288D1
lbshade5 = #039BE5
lbshade4 = #03A9F4
lbshade3 = #29B6F6
lbshade2 = #4FC3F7
lbshade1 = #81D4FA

; Light-Green
lgshade8 = #33691E
lgshade7 = #558B2F
lgshade6 = #689F38
lgshade5 = #7CB342
lgshade4 = #8BC34A
lgshade3 = #9CCC65
lgshade2 = #AED581
lgshade1 = #C5E1A5

; Lime
lishade8 = #827717
lishade7 = #9E9D24
lishade6 = #AFB42B
lishade5 = #C0CA33
lishade4 = #CDDC39
lishade3 = #D4E157
lishade2 = #DCE775
lishade1 = #E6EE9C

; Orange
orange800 = #E65100
orange700 = #EF6C00
orange600 = #F57C00
orange500 = #FB8C00
orange400 = #FF9800
orange300 = #FFA726
orange200 = #FFB74D
orange100 = #FFCC80

; Pink
pishade8 = #880E4F
pishade7 = #AD1457
pishade6 = #C2185B
pishade5 = #D81B60
pishade4 = #E91E63
pishade3 = #EC407A
pishade2 = #F06292
pishade1 = #F48FB1

; Purple
prshade8 = #4A148C
prshade7 = #6A1B9A
prshade6 = #7B1FA2
prshade5 = #8E24AA
prshade4 = #9C27B0
prshade3 = #AB47BC
prshade2 = #BA68C8
prshade1 = #CE93D8

; Red
red800 = #B71C1C
red700 = #C62828
red600 = #D32F2F
red500 = #E53935
red400 = #EE413D
red300 = #EF5350
red200 = #E57373
red100 = #EF9A9A

; Teal
teshade8 = #004D40
teshade7 = #00695C
teshade6 = #00796B
teshade5 = #00897B
teshade4 = #009688
teshade3 = #26A69A
teshade2 = #4DB6AC
teshade1 = #80CBC4

; Yellow
yeshade8 = #F57F17
yeshade7 = #F9A825
yeshade6 = #FBC02D
yeshade5 = #FDD835
yeshade4 = #FFEB3B
yeshade3 = #FFEE58
yeshade2 = #FFF176
yeshade1 = #FFF59D

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;	    __________  ______
;;	   / ____/ __ \/ ____/
;;	  / __/ / / / / /_
;;	 / /___/ /_/ / __/
;;	/_____/\____/_/
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
