#!/bin/sh

# Этот файл нужно включить в .bashrc или .zshrc

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Команды в verbose mode по-умолчанию
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias mkd="mkdir -pv"
alias ls='exa --group-directories-first --classify --sort=extension --icons'
alias ll='exa --group-directories-first \
              --long \
              --classify \
              --grid \
              --links \
              --header \
              --git \
              --sort=extension \
              --icons'
alias lsa='ls --all'
alias lla='ll --all'
alias lt='exa --tree --level=2 --classify --sort=ext --icons'
alias nnn="nnn -e"
alias g=git
alias glg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glga="glg --all"
alias gcmm='git commit -m'
alias gcma='git commit --amend'
alias gsw='git switch'
alias gchb='git checkout -b'
alias gst='git status'
alias gdf='git diff'
alias gdfc='git diff --cached'
alias cdd='cd ~/.dotfiles'
alias cdx='cd ~/.xi'
alias cdc='cd ~/code'
alias cdl='cd ~/cloud/mailru/G.Prog'
alias vec="python -m venv .venv"
alias vea=". .venv/bin/activate"
alias ved="deactivate"
alias vifm="$HOME/.config/vifm/scripts/vifmrun"
alias rgf="rg --files | rg"
alias ghc='gh repo clone `gh repo list --limit=1000 | awk '"'"'{ print $1 }'"'"' | fzf`'
alias vpnu='wg-quick up vpn'
alias vpnd='wg-quick down vpn'

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	z="zathura"
