#+TITLE: BL's Doom Emacs Config
#+AUTHOR: Ilay Lisin aka BlackLacost (DT)

* Beacon
Never lose your cursor.  When you scroll, your cursor will shine!  This is a global minor-mode. Turn it on everywhere with:

#+begin_src emacs-lisp
(beacon-mode 1)
#+end_src

* Doom
Doom exposes five (optional) variables for controlling fonts in Doom:

- `doom-variable-pitch-font' -- a non-monospace font (where applicable)
- `doom-big-font' -- used for `doom-big-font-mode'; use this for presentations or streaming.
- `doom-unicode-font' -- for unicode glyphs
- `doom-serif-font' -- for the `fixed-pitch-serif' face

See 'C-h v doom-font' for documentation and more examples of what they accept. For example:

setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
     doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))

If you or Emacs can't find your font, use 'M-x describe-font' to look them up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to refresh your font settings. If Emacs still can't find your font, it likely wasn't installed correctly. Font issues are rarely Doom issues!

There are two ways to load a theme. Both assume the theme is installed and available. You can either set `doom-theme' or manually load a theme with the `load-theme' function. This is the default:

#+begin_src emacs-lisp
(setq doom-theme 'doom-material)
#+end_src

* Line Settings
I set comment-line to 'SPC t /'. The standard Emacs keybinding for comment-line is 'C-x C-;'.  The other keybindings are for commands that toggle on/off various line-related settings.  Doom Emacs uses 'SPC t' for "toggle" commands, so I choose 'SPC t' plus 'key' for those bindings.

This determines the style of line numbers in effect:
- 'nul -- line numbers are disabled
- 'relative -- relative line numbers
- 'visual -- relative line numbers, but usefull if you're using folding in org mode

| COMMAND                  | DESCRIPTION                                 | KEYBINDING |
|--------------------------+---------------------------------------------+------------|
| comment-line             | /Comment or uncomment lines/                | SPC t /    |
| hl-line-mode             | /Toggle line highlighting in current frame/ | SPC t h    |
| global-hl-line-mode      | /Toggle line highlighting globally/         | SPC t H    |
| doom/toggle-line-numbers | /Toggle line numbers/                       | SPC t l    |
| toggle-truncate-lines    | /Toggle truncate lines/                     | SPC t t    |

#+begin_src emacs-lisp
(setq display-line-numbers 'visual)
(map! :leader
      (:prefix ("t" . "toggle")
       :desc "Comment or uncomment lines" "/" #'comment-line
       :desc "Toggle line numbers" "l" #'doom/toggle-line-numbers
       :desc "Toggle line highlight in frame" "h" #'hl-line-mode
       :desc "Toggle line highlight globally" "H" #'global-hl-line-mode
       :desc "Toggle truncate lines" "t" #'toggle-truncate-lines))
#+end_src

* Fonts
Settings related to fonts within Doom Emacs:

- ‘doom-font’ – standard monospace font that is used for most things in Emacs.
- ‘doom-variable-pitch-font’ – variable font which is useful in some Emacs plugins.
- ‘doom-big-font’ – used in doom-big-font-mode; useful for presentations.
- ‘font-lock-comment-face’ – for comments.
- ‘font-lock-keyword-face’ – for keywords with special significance like ‘setq’ in elisp.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Source Code Pro" :size 18)
      doom-variable-pitch-font (font-spec :family "Ubuntu" :size 18)
      doom-big-font (font-spec :family "Source Code Pro" :size 28))
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))
#+end_src

* Org Mode
I wrapped most of this block in (after! org).  Without this, my settings might be evaluated too early, which will result in my settings being overwritten by Doom's defaults.  I have also enabled org-journal, org-superstar and org-roam by adding (+journal +pretty +roam2) to the org section of my Doom Emacs init.el.

=NOTE:= I have the location of my Org directory and Roam directory in $HOME/nc/ which is a Nextcloud folder that allows me to instantly sync all of my Org work between my home computer and my office computer.

** Agenda

#+begin_src emacs-lisp
(after! org
  ;; TODO Agenda doesn't work in hidden directories and subdirectories
  ;; (setq org-agenda-files '("~/cloud/mailru/org/gtd/inbox.org" "~/cloud/mailru/org/gtd/gtd.org" "~/cloud/mailru/org/gtd/tickler.org" "~/cloud/mailru/org/habit.org")
  (setq org-agenda-files (list "gtd/inbox.org" "gtd/gtd.org" "gtd/tickler.org" "habit.org")
        org-agenda-start-with-log-mode t
        org-log-done 'time     ; Log time when task done
        org-log-reschedule nil
        ;; NOTE I don't undestand this
        org-log-into-drawer t))
#+end_src

Keywords

*** Custom agenda views
Configure custom agenda views

#+begin_src emacs-lisp
(after! org
  (setq org-agenda-custom-commands
        '(("d" "Dashboard"
           ((agenda "" ((org-deadline-warning-days 7)))
            (tags-todo "+PRIORITY=\"A\""
                       ((org-agenda-overriding-header "High Priority")))
            (todo "NEXT"
                  ((org-agenda-overriding-header "Next Actions")
                   (org-agenda-max-todos nil)))
            (todo "TODO"
                  ((org-agenda-overriding-header "Unprocessed Inbox Tasks")
                   (org-agenda-text-search-extra-files nil)))))

          ("n" "Next Tasks"
           ((agenda "" ((org-deadline-warning-days 7)))
            (todo "NEXT" ((org-agenda-overriding-header "Next Tasks")))))

          ("W" "Work Tasks" tags-todo "+work-email") ;; - for exclude tag

          ;; Low-effort next actions
          ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
           ((org-agenda-overriding-header "Low Effort Tasks")
            (org-agenda-max-todos 20)
            (org-agenda-files org-agenda-files)))

          ("w" "Workflow Status"
           ((todo "WAIT"
                  ((org-agenda-overriding-header "Waiting on External")
                   (org-agenda-files org-agenda-files)))
            (todo "REVIEW"
                  ((org-agenda-overriding-header "In Review")
                   (org-agenda-files org-agenda-files)))
            (todo "PLAN"
                  ((org-agenda-overriding-header "In Planning")
                   (org-agenda-todo-list-sublevels nil)
                   (org-agenda-files org-agenda-files)))
            (todo "BACKLOG"
                  ((org-agenda-overriding-header "Project Backlog")
                   (org-agenda-todo-list-sublevels nil)
                   (org-agenda-files org-agenda-files)))
            (todo "READY"
                  ((org-agenda-overriding-header "Ready for Work")
                   (org-agenda-files org-agenda-files)))
            (todo "ACTIVE"
                  ((org-agenda-overriding-header "Active Projects")
                   (org-agenda-files org-agenda-files)))
            (todo "COMPLETED"
                  ((org-agenda-overriding-header "Completed Projects")
                   (org-agenda-files org-agenda-files)))
            (todo "CANC"
                  ((org-agenda-overriding-header "Cancelled Projects")
                   (org-agenda-files org-agenda-files))))))))
#+end_src

** Capture Templates

- Tasks
- Meeting notes
- Table entries
- Journal entries

- =%a=: link to the file from where you called the capture command

#+begin_src emacs-lisp
(defun dw/read-file-as-string (path)
  (with-temp-buffer
    (insert-file-contents path)
    (buffer-string)))

(after! org
  (setq org-capture-templates
        `(("i" "Inbox" entry (file "gtd/inbox.org")
           ,(concat "* TODO %?\n"
                    "/Entered on/ %U"))
          ("@" "Inbox [mu4e]" entry (file "inbox.org")
           ,(concat "* TODO Process \"%a\" %?\n"
                    "/Entered on/ %U"))

          ("t" "Tasks / Projects")
          ("tt" "Task" entry (file "gtd/inbox.org")
           "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)
          ("ts" "Clocked Entry Subtask" entry (clock)
           "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

          ("j" "Journal Entries")
          ("jj" "Journal" entry
           (file+olp+datetree "~/cloud/mailru/org/journal.org")
           "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
           ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
           :clock-in :clock-resume
           :empty-lines 1)
          ("jm" "Meeting" entry
           (file+olp+datetree "~/cloud/mailru/org/journal.org")
           "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
           :clock-in :clock-resume
           :empty-lines 1)

          ("w" "Workflows")
          ("we" "Checking Email" entry (file+olp+datetree "~/cloud/mailru/org/journal.org")
           "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

          ("m" "Metrics Capture")
          ("mw" "Weight" table-line (file+headline "~/cloud/mailru/org/metrics.org" "Weight")
           "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)
          ("mf" "Fitness" table-line (file+headline "~/cloud/mailru/org/metrics.org" "Fitness")
           "| %U | %^{Type} | %^{Notes} |" :kill-buffer t))))
#+end_src

** Deft

#+begin_src emacs-lisp
(after! org
  (setq deft-extensions '("txt" "tex" "org")
        deft-directory "~/cloud/mailru/org"
        deft-recursive t))
#+end_src

** File Paths
If you use `org' and don't want your org files in the default location below, change `org-directory'. It must be set before org loads!

#+begin_src emacs-lisp
(setq org-directory "~/cloud/mailru/org/")
#+end_src

** GTD
#+begin_src emacs-lisp
(use-package! org-gtd
  :after org
  :config
  (map! :leader
        (:prefix ("d" . "GDT")
         :desc "Add" "a" #'org-gtd-capture
         :desc "Engage" "e" #'org-gtd-engage
         :desc "Process Inbox" "p" #'org-gtd-process-inbox
         :desc "Show All Next" "n" #'org-gtd-show-all-next
         :desc "Show Stuck Projects" "s" #'org-gtd-show-all-next
         :desc "Choose" "c" #'org-gtd-choose
         ))
  (define-key org-gtd-process-map (kbd "C-c c") #'org-gtd-choose)
  )
#+end_src

** Habit

#+begin_src emacs-lisp
;; (require 'org-habit)
;; (add-tolist 'org-modules 'org-habit)
(after! org
  (setq! org-habit-graph-column 60))
#+end_src

** Journal

#+begin_src emacs-lisp
(after! org
  (setq org-journal-date-prefix "#+TITLE: "
        org-journal-time-prefix "* "
        org-journal-date-format "%a, %Y-%m-%d"
        org-journal-file-format "%Y-%m-%d.org"))
#+end_src

** Org Roam

| COMMAND                            | DESCRIPTION                     | KEYBINDING  |
|------------------------------------+---------------------------------+-------------|
| org-roam-buffer-toggle             | toggle display of roam buffer   | SPC n r r   |
| org-roam-node-file                 | org roam node file              | SPC n r f   |
| org-roam-node-insert               | org roam node insert            | SPC n r i   |
| org-roam-node-insert-immediate     | org roam node insert immediate  | SPC n r I   |
| org-roam-alias-add                 | org roam add alias              | SPC m m o a |
| org-roam-alias-remove              | org roam remove alias           | SPC m m o A |
| org-roam-dailies-capture-today     | create daily-note for today     | SPC n r d T |
| org-roam-dailies-capture-date      | create daily-note for any date  | SPC n r d D |
| org-roam-dailies-capture-tomorrow  | create daily-note for tomorrow  | SPC n r d M |
| org-roam-dailies-capture-yesterday | create daily-note for yesterday | SPC n r d Y |
| org-roam-dailies-find-date         | org roam dailies find date      | SPC n r d d |
| org-roam-dailies-find-today        | org roam dailies find today     | SPC n r d t |
| org-roam-dailies-find-tomorrow     | org roam dailies find tomorrow  | SPC n r d m |
| org-roam-dailies-find-yesterday    | org roam dailies find yesterday | SPC n r d y |
| org-roam-dailies-capture-today     | Create daily-note for today     | SPC n r d T |
| org-id-get-create                  | create ID for Heading           | SPC m I     |
| completion-at-point                | completion in [[]]              | C-M-i       |

Daily directory must be *RELATIVE* to roam directory.

#+begin_src emacs-lisp
(after! org-roam
  (setq org-roam-directory "~/cloud/mailru/org/roam"
        org-roam-dailies-directory "daily/" ; daily is default, put here for explicit
        org-roam-completion-everywhere t  ; Try complete roam links everywhere (outside of [[]])
        org-roam-capture-templates
        '(("d" "default" plain
           (file "~/cloud/mailru/org/roam/templates/default_template.org")
           :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
           :unnarrowed t)
          ("b" "book notes" plain
           (file "~/cloud/mailru/org/roam/templates/book_note_template.org")
           :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
           :unnarrowed t)
          ("p" "project" plain
           (file "~/cloud/mailru/org/roam/templates/project_template.org")
           :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: :project:")
           :unnarrowed t)))
  ;; TODO work, but error when start emacs
  ;; (map! ("C-M-i" . completion-at-point))
  ;; NOTE try but doesn't work
  ;; (define-key global-map (kbd "C-M-i") #'completion-at-point)
  (map! :leader
        :desc "Insert immediate node" "n r I" #'org-roam-node-insert-immediate))
#+end_src

*** Immediate Note

Create immediate default note.

#+begin_src emacs-lisp
(defun org-roam-node-insert-immediate (arg &rest args)
  (interactive "P")
  (let ((args (cons arg args))
        (org-roam-capture-templates (list (append (car org-roam-capture-templates)
                                                  '(:immediate-finish t)))))
    (apply #'org-roam-node-insert args)))
#+end_src

*** [[https://youtu.be/CUkuyW6hr18?t=295][Agenda list by tag]]

#+begin_src emacs-lisp
;; (defun my/org-roam-filter-by-tag (tag-name)
;;   (lambda (node)
;;     (member tag-name (org-roam-node-tags node))))

;; (defun my/org-roam-list-notes-by-tag (tag-name)
;;   (mapcar #'org-roam-node-file
;;           (seq-filter
;;            (my/org-roam-filter-by-tag tag-name)
;;            (org-roam-node-list))))

;; (defun my/org-roam-refresh-agenda-list ()
;;   (interactive)
;;   (setq org-agenda-files (my/org-roam-list-notes-by-tag "project")))

;; Build the agenda list the first time for the session
;; (my/org-roam-refresh-agenda-list)
#+end_src

** Priorities Colors & Icons
Emoji for task priority.

#+begin_src emacs-lisp
(use-package org-fancy-priorities
  :ensure t
  :hook
  (org-mode . org-fancy-priorities-mode)
  :config
  (setq org-fancy-priorities-list '("⚡" "⬆" "⬇" "☕")))
#+end_src

Colors for priority

#+begin_src emacs-lisp
;; (after! org
;;   (setq org-priority-faces
;;         '((?A :foreground "#e45649")
;;           (?B :foreground "#da8548")
;;           (?C :foreground "#0098dd"))))
#+end_src

** Refiling

#+begin_src emacs-lisp
(after! org
  (setq org-refile-targets
        '(("~/cloud/mailru/org/gtd/gtd.org" :maxlevel . 3)
          ("~/cloud/mailru/org/gtd/someday.org" :level . 1)
          ("~/cloud/mailru/org/gtd/tickler.org" :maxlevel . 2)))
  ;; Save Org buffers after refiling!
  (advice-add 'org-refile :after 'org-save-all-org-buffers))
#+end_src

** Repeat Tasks
When repeat task is DONE, auto set NEXT status.

#+begin_src emacs-lisp
(after! org
  (setq org-todo-repeat-to-state "NEXT"))
#+end_src
** Tags
Default tags when org-set-tags-command.

When select tag use:

- =SPC= - clear all tags
- =RET= - add tag and exit

#+begin_src emacs-lisp
(after! org
  (setq org-tag-alist
        '((:startgroup)
          ;; Put mutually exclusive tags here
          (:endgroup)
          ("@errand" . ?E)
          ("@home" . ?H)
          ("@phone" . ?P)
          ("@work" . ?W)
          ("@street" . ?S)
          ("agenda" . ?a)
          ("planning" . ?p)
          ("publish" . ?P)
          ("batch" . ?b)
          ("note" . ?n)
          ("idea" . ?i))))
#+end_src

Colors

** Todo keywords

#+begin_src emacs-lisp
(after! org
  (setq org-todo-keywords      ; This overwrites the default Doom org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
          (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)"))))
        ;; org-todo-keyword-faces
        ;; `(("TODO" :foreground "#7c7c75" :weight normal :underline t)
        ;;   ("WAIT" :foreground "#9f7efe" :weight normal :underline t)
        ;;   ("NEXT" :foreground "#0098dd" :weight normal :underline t)
        ;;   ("DONE" :foreground "#50a14f" :weight normal :underline t)
        ;;   ("CANC" :foreground "#ff6480" :weight normal :underline t))
#+end_src

* Registers
Emacs registers are compartments where you can save text, rectangles and positions for later use. Once you save text or a rectangle in a register, you can copy it into the buffer once or many times; once you save a position in a register, you can jump back to that position once or many times.  The default GNU Emacs keybindings for these commands (with the exception of counsel-register) involves 'C-x r' followed by one or more other keys.  I wanted to make this a little more user friendly, and since I am using Doom Emacs, I choose to replace the 'C-x r' part of the key chords with 'SPC r'.

| COMMAND                          | DESCRIPTION                        | KEYBINDING |
|----------------------------------+------------------------------------+------------|
| copy-to-register                 | /Copy to register/                 | SPC r c    |
| frameset-to-register             | /Frameset to register/             | SPC r f    |
| insert-register                  | /Insert contents of register/      | SPC r i    |
| jump-to-register                 | /Jump to register/                 | SPC r j    |
| list-registers                   | /List registers/                   | SPC r l    |
| number-to-register               | /Number to register/               | SPC r n    |
| counsel-register                 | /Interactively choose a register/  | SPC r r    |
| view-register                    | /View a register/                  | SPC r v    |
| window-configuration-to-register | /Window configuration to register/ | SPC r w    |
| increment-register               | /Increment register/               | SPC r +    |
| point-to-register                | /Point to register/                | SPC r SPC  |

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("r" . "registers")
       :desc "Copy to register" "c" #'copy-to-register
       :desc "Frameset to register" "f" #'frameset-to-register
       :desc "Insert contents of register" "i" #'insert-register
       :desc "Jump to register" "j" #'jump-to-register
       :desc "List registers" "l" #'list-registers
       :desc "Number to register" "n" #'number-to-register
       :desc "Interactively choose a register" "r" #'counsel-register
       :desc "View a register" "v" #'view-register
       :desc "Window configuration to register" "w" #'window-configuration-to-register
       :desc "Increment register" "+" #'increment-register
       :desc "Point to register" "SPC" #'point-to-register))
#+end_src

* Shell
Settings for the various shells and terminal emulators within Emacs.

** [[https://www.gnu.org/software/emacs/manual/html_mono/eshell.html][Eshell]]

#+begin_src emacs-lisp
(setq eshell-aliases-file "~/.config/doom/eshell/aliases"
      eshell-history-size 5000
      eshell-buffer-maximum-lines 5000
      eshell-hist-ignoredups t
      eshell-scroll-to-bottom-on-input t
      eshell-destroy-buffer-when-process-dies t
      eshell-visual-commands'("bash" "htop" "ssh" "top"))

(map! :leader
      (:prefix ("e". "Terminal")
       :desc "Eshell" "s" #'eshell
       :desc "Eshell popup toggle" "t" #'+eshell/toggle
       :desc "Consult terminal history" "h" #'consult-history
       :desc "Vterm popup toggle" "v" #'+vterm/toggle))
#+end_src

* Spell

#+begin_src emacs-lisp
(after! flyspell
  (setq flyspell-default-dictionary "en_US"))
#+end_src

* User Info
Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets. It is optional.

#+begin_src emacs-lisp
(setq user-full-name "Ilya Lisin"
      user-mail-address "blacklacost@gmail.com")
#+end_src

* Other


;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

* Example create youtube link
(defun make-youtube-link (youtube_id)
  (browse-url (concat "https://www.youtube.com/embed/" youtube_id)))

(after! org
  (org-add-link-type "yt" #'make-youtube-link))
